refactor: remove jquery
esx-framework/esx_property pull request #23
Opened 2023-08-09 14:29 UTC by MoskalykA

2023-08-18 18:04 UTC, Gellipapa requested changes

2023-08-18 18:04 UTC, Gellipapa commented on client/html/copy.html
> +        var node = document.createElement("textarea");
Please change var to let.

2023-08-18 20:45 UTC, Gellipapa approved these changes

2023-10-16 18:48 UTC, bitpredator approved these changes

2024-01-18 21:54 UTC, Gellipapa commented
Hi! @MoskalykA In the future the property system will be rewritten so for now I don't accept this, it works the way it works now.

2024-01-18 21:54 UTC, closed without merging